title: Pitbull_gp's awesome page
author: Pitbull_gp
email: aka.pitbull.pp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here is were I brag about all my accomplishments

# social links
#twitter_username: your-twitter-handle
github_username:  Phillipptrs

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
